USE ls_motors;

-- Sports
UPDATE vehicule SET Image='alpha.png' WHERE NomModele='Alpha';
UPDATE vehicule SET Image='bestiagts.png' WHERE NomModele='Bestia GTS';
UPDATE vehicule SET Image='buffalo.png' WHERE NomModele='Buffalo';
UPDATE vehicule SET Image='buffalo2.png' WHERE NomModele='Buffalo S';
UPDATE vehicule SET Image='carbonizzare.png' WHERE NomModele='Carbonizzare';
UPDATE vehicule SET Image='comet.png' WHERE NomModele='Comet';
UPDATE vehicule SET Image='comet5.png' WHERE NomModele='Comet5';
UPDATE vehicule SET Image='comet6.png' WHERE NomModele='Comet6';
UPDATE vehicule SET Image='coquette.png' WHERE NomModele='Coquette';
UPDATE vehicule SET Image='drafter.png' WHERE NomModele='Drafter';
UPDATE vehicule SET Image='dynasty.png' WHERE NomModele='Dynasty';
UPDATE vehicule SET Image='elegy.png' WHERE NomModele='Elegy RH8';
UPDATE vehicule SET Image='elegy2.png' WHERE NomModele='Elegy Retro';
UPDATE vehicule SET Image='flashgt.png' WHERE NomModele='Flash GT';
UPDATE vehicule SET Image='fusilade.png' WHERE NomModele='Fusilade';
UPDATE vehicule SET Image='futo.png' WHERE NomModele='Futo';
UPDATE vehicule SET Image='futo2.png' WHERE NomModele='Futo2';
UPDATE vehicule SET Image='gb200.png' WHERE NomModele='GB200';
UPDATE vehicule SET Image='imorgon.png' WHERE NomModele='Imorgon';
UPDATE vehicule SET Image='infernus2.png' WHERE NomModele='Infernus2';
UPDATE vehicule SET Image='issi7.png' WHERE NomModele='Issi7';
UPDATE vehicule SET Image='italigto.png' WHERE NomModele='Italigto';
UPDATE vehicule SET Image='jester.png' WHERE NomModele='Jester';
UPDATE vehicule SET Image='jester3.png' WHERE NomModele='Jester3';
UPDATE vehicule SET Image='jester4.png' WHERE NomModele='Jester4';
UPDATE vehicule SET Image='jugular.png' WHERE NomModele='Jugular';
UPDATE vehicule SET Image='khamelion.png' WHERE NomModele='Khamelion';
UPDATE vehicule SET Image='komoda.png' WHERE NomModele='Komoda';
UPDATE vehicule SET Image='kuruma.png' WHERE NomModele='Kuruma';
UPDATE vehicule SET Image='lynx.png' WHERE NomModele='Lynx';
UPDATE vehicule SET Image='mamba.png' WHERE NomModele='Mamba';
UPDATE vehicule SET Image='massacro.png' WHERE NomModele='Massacro';
UPDATE vehicule SET Image='michelli.png' WHERE NomModele='Michelli';
UPDATE vehicule SET Image='neon.png' WHERE NomModele='Neon';
UPDATE vehicule SET Image='ninef.png' WHERE NomModele='9F';
UPDATE vehicule SET Image='ninef2.png' WHERE NomModele='9F Cabrio';
UPDATE vehicule SET Image='omnis.png' WHERE NomModele='Omnis';
UPDATE vehicule SET Image='paragon.png' WHERE NomModele='Paragon';
UPDATE vehicule SET Image='pariah.png' WHERE NomModele='Pariah';
UPDATE vehicule SET Image='penumbra.png' WHERE NomModele='Penumbra';
UPDATE vehicule SET Image='penumbra2.png' WHERE NomModele='Penumbra2';
UPDATE vehicule SET Image='peyote2.png' WHERE NomModele='Peyote Gasser';
UPDATE vehicule SET Image='prairie.png' WHERE NomModele='Prairie';
UPDATE vehicule SET Image='rapidgt.png' WHERE NomModele='Rapid GT';
UPDATE vehicule SET Image='remus.png' WHERE NomModele='Remus';
UPDATE vehicule SET Image='rt3000.png' WHERE NomModele='RT3000';
UPDATE vehicule SET Image='ruston.png' WHERE NomModele='Ruston';
UPDATE vehicule SET Image='revolter.png' WHERE NomModele='Revolter';
UPDATE vehicule SET Image='schafter4.png' WHERE NomModele='Schafter V12';
UPDATE vehicule SET Image='schafter5.png' WHERE NomModele='Schafter4';
UPDATE vehicule SET Image='schlagen.png' WHERE NomModele='Schlagen';
UPDATE vehicule SET Image='seven70.png' WHERE NomModele='Seven70';
UPDATE vehicule SET Image='specter.png' WHERE NomModele='Specter';
UPDATE vehicule SET Image='stratum.png' WHERE NomModele='Stratum' AND ID_Categorie=(SELECT ID FROM categorie WHERE Libelle='Sports');
UPDATE vehicule SET Image='streiter.png' WHERE NomModele='Streiter';
UPDATE vehicule SET Image='sugoi.png' WHERE NomModele='Sugoi';
UPDATE vehicule SET Image='sultan.png' WHERE NomModele='Sultan';
UPDATE vehicule SET Image='sultan2.png' WHERE NomModele='Sultan2';
UPDATE vehicule SET Image='sultan3.png' WHERE NomModele='Sultan3';
UPDATE vehicule SET Image='sultanrs.png' WHERE NomModele='Sultan RS';
UPDATE vehicule SET Image='surano.png' WHERE NomModele='Surano';
UPDATE vehicule SET Image='swinger.png' WHERE NomModele='Swinger';
UPDATE vehicule SET Image='tampa2.png' WHERE NomModele='Tampa2' AND ID_Categorie=(SELECT ID FROM categorie WHERE Libelle='Sports');
UPDATE vehicule SET Image='torero.png' WHERE NomModele='Torero';
UPDATE vehicule SET Image='tropos.png' WHERE NomModele='Tropos';
UPDATE vehicule SET Image='turismo2.png' WHERE NomModele='Turismo2';
UPDATE vehicule SET Image='vectre.png' WHERE NomModele='Vectre';
UPDATE vehicule SET Image='vstr.png' WHERE NomModele='Vstr';
UPDATE vehicule SET Image='zion3.png' WHERE NomModele='Zion3' AND ID_Categorie=(SELECT ID FROM categorie WHERE Libelle='Sports');
UPDATE vehicule SET Image='zr350.png' WHERE NomModele='ZR350';
UPDATE vehicule SET Image='growler.png' WHERE NomModele='Growler';
UPDATE vehicule SET Image='comet6.png' WHERE NomModele='Comet S2 Cabrio';
UPDATE vehicule SET Image='feltzer2.png' WHERE NomModele='Feltzer';

-- Sport Classics
UPDATE vehicule SET Image='btype.png' WHERE NomModele='Btype';
UPDATE vehicule SET Image='btype2.png' WHERE NomModele='Btype Hotrod';
UPDATE vehicule SET Image='btype3.png' WHERE NomModele='Btype Luxe';
UPDATE vehicule SET Image='casco.png' WHERE NomModele='Casco';
UPDATE vehicule SET Image='coquette2.png' WHERE NomModele='Coquette Classic';
UPDATE vehicule SET Image='gt500.png' WHERE NomModele='GT500';
UPDATE vehicule SET Image='stingergt.png' WHERE NomModele='Stirling GT';
UPDATE vehicule SET Image='tornado.png' WHERE NomModele='Tornado Custom';
UPDATE vehicule SET Image='peyote.png' WHERE NomModele='Peyote Custom';
UPDATE vehicule SET Image='viseris.png' WHERE NomModele='Viseris';
UPDATE vehicule SET Image='ztype.png' WHERE NomModele='Z-Type';

-- Super
UPDATE vehicule SET Image='adder.png' WHERE NomModele='Adder';
UPDATE vehicule SET Image='banshee2.png' WHERE NomModele='Banshee 900R';
UPDATE vehicule SET Image='bullet.png' WHERE NomModele='Bullet';
UPDATE vehicule SET Image='champion.png' WHERE NomModele='Champion';
UPDATE vehicule SET Image='cyclone.png' WHERE NomModele='Cyclone';
UPDATE vehicule SET Image='cyclone2.png' WHERE NomModele='Cyclone2';
UPDATE vehicule SET Image='entityxf.png' WHERE NomModele='Entity XF';
UPDATE vehicule SET Image='entity2.png' WHERE NomModele='Entity XXR';
UPDATE vehicule SET Image='fmj.png' WHERE NomModele='FMJ';
UPDATE vehicule SET Image='gp1.png' WHERE NomModele='GP1';
UPDATE vehicule SET Image='ignus.png' WHERE NomModele='Ignus';
UPDATE vehicule SET Image='infernus.png' WHERE NomModele='Infernus';
UPDATE vehicule SET Image='krieger.png' WHERE NomModele='Krieger';
UPDATE vehicule SET Image='italirsx.png' WHERE NomModele='Itali RSX';
UPDATE vehicule SET Image='nero.png' WHERE NomModele='Nero';
UPDATE vehicule SET Image='nero2.png' WHERE NomModele='Nero Custom';
UPDATE vehicule SET Image='osiris.png' WHERE NomModele='Osiris';
UPDATE vehicule SET Image='penetrator.png' WHERE NomModele='Penetrator';
UPDATE vehicule SET Image='pfister811.png' WHERE NomModele='Pfister Astron Custom';
UPDATE vehicule SET Image='s80.png' WHERE NomModele='RE-7B';
UPDATE vehicule SET Image='s95.png' WHERE NomModele='S80RR';
UPDATE vehicule SET Image='sc1.png' WHERE NomModele='SC1';
UPDATE vehicule SET Image='sheava.png' WHERE NomModele='Sheava';
UPDATE vehicule SET Image='t20.png' WHERE NomModele='T20';
UPDATE vehicule SET Image='taipan.png' WHERE NomModele='Taipan';
UPDATE vehicule SET Image='tezeract.png' WHERE NomModele='Tezeract';
UPDATE vehicule SET Image='thrax.png' WHERE NomModele='Thrax';
UPDATE vehicule SET Image='turismor.png' WHERE NomModele='Turismo R';
UPDATE vehicule SET Image='tyrant.png' WHERE NomModele='Tyrant';
UPDATE vehicule SET Image='tyrus.png' WHERE NomModele='Tyrus';
UPDATE vehicule SET Image='vacca.png' WHERE NomModele='Vacca';
UPDATE vehicule SET Image='vagner.png' WHERE NomModele='Vagner';
UPDATE vehicule SET Image='vigilante.png' WHERE NomModele='Vigilante';
UPDATE vehicule SET Image='visione.png' WHERE NomModele='Visione';
UPDATE vehicule SET Image='zeno.png' WHERE NomModele='Zeno';
UPDATE vehicule SET Image='zentorno.png' WHERE NomModele='Zentorno';
UPDATE vehicule SET Image='emerus.png' WHERE NomModele='Emerus';
UPDATE vehicule SET Image='deveste.png' WHERE NomModele='Deveste Eight';
UPDATE vehicule SET Image='italigto.png' WHERE NomModele='Itali GTO Stinger TT';
UPDATE vehicule SET Image='torero2.png' WHERE NomModele='Torero XO';
UPDATE vehicule SET Image='virtue.png' WHERE NomModele='Virtue';
UPDATE vehicule SET Image='lm87.png' WHERE NomModele='LM87';
UPDATE vehicule SET Image='cyclone2.png' WHERE NomModele='Cyclone Custom';
UPDATE vehicule SET Image='furia.png' WHERE NomModele='Furia';
UPDATE vehicule SET Image='reaper.png' WHERE NomModele='Reaper';
UPDATE vehicule SET Image='xa21.png' WHERE NomModele='X80 Proto';
UPDATE vehicule SET Image='etr1.png' WHERE NomModele='ETR1';

-- Muscles
UPDATE vehicule SET Image='blade.png' WHERE NomModele='Blade';
UPDATE vehicule SET Image='buccaneer.png' WHERE NomModele='Buccaneer';
UPDATE vehicule SET Image='buccaneer2.png' WHERE NomModele='Buccaneer Rider';
UPDATE vehicule SET Image='chino.png' WHERE NomModele='Chino';
UPDATE vehicule SET Image='chino2.png' WHERE NomModele='Chino Luxe';
UPDATE vehicule SET Image='clique.png' WHERE NomModele='Clique';
UPDATE vehicule SET Image='deviant.png' WHERE NomModele='Deviant';
UPDATE vehicule SET Image='dominator.png' WHERE NomModele='Dominator';
UPDATE vehicule SET Image='dominator2.png' WHERE NomModele='Dominator2';
UPDATE vehicule SET Image='dominator3.png' WHERE NomModele='Dominator3';
UPDATE vehicule SET Image='dominator4.png' WHERE NomModele='Dominator GTX';
UPDATE vehicule SET Image='dukes.png' WHERE NomModele='Dukes';
UPDATE vehicule SET Image='dukes3.png' WHERE NomModele='Dukes3';
UPDATE vehicule SET Image='ellie.png' WHERE NomModele='Ellie';
UPDATE vehicule SET Image='faction.png' WHERE NomModele='Faction';
UPDATE vehicule SET Image='faction2.png' WHERE NomModele='Faction Rider';
UPDATE vehicule SET Image='faction3.png' WHERE NomModele='Faction3 (Donk)';
UPDATE vehicule SET Image='gauntlet.png' WHERE NomModele='Gauntlet';
UPDATE vehicule SET Image='gauntlet2.png' WHERE NomModele='Gauntlet2';
UPDATE vehicule SET Image='gauntlet3.png' WHERE NomModele='Gauntlet3';
UPDATE vehicule SET Image='gauntlet4.png' WHERE NomModele='Gauntlet4';
UPDATE vehicule SET Image='gauntlet5.png' WHERE NomModele='Gauntlet5';
UPDATE vehicule SET Image='hermes.png' WHERE NomModele='Hermes';
UPDATE vehicule SET Image='hustler.png' WHERE NomModele='Hustler';
UPDATE vehicule SET Image='hotknife.png' WHERE NomModele='Hotknife';
UPDATE vehicule SET Image='impaler.png' WHERE NomModele='Impaler';
UPDATE vehicule SET Image='impaler2.png' WHERE NomModele='Impaler2';
UPDATE vehicule SET Image='impaler3.png' WHERE NomModele='Impaler3';
UPDATE vehicule SET Image='impaler4.png' WHERE NomModele='Impaler4';
UPDATE vehicule SET Image='nightshade.png' WHERE NomModele='Nightshade';
UPDATE vehicule SET Image='phoenix.png' WHERE NomModele='Phoenix';
UPDATE vehicule SET Image='picador.png' WHERE NomModele='Picador';
UPDATE vehicule SET Image='ratloader.png' WHERE NomModele='Ratloader';
UPDATE vehicule SET Image='ratloader2.png' WHERE NomModele='Ratloader2';
UPDATE vehicule SET Image='ruiner.png' WHERE NomModele='Ruiner';
UPDATE vehicule SET Image='ruiner2.png' WHERE NomModele='Ruiner2';
UPDATE vehicule SET Image='sabregt.png' WHERE NomModele='Sabre Turbo';
UPDATE vehicule SET Image='sabregt2.png' WHERE NomModele='Sabre Turbo Custom';
UPDATE vehicule SET Image='tampa.png' WHERE NomModele='Tampa';
UPDATE vehicule SET Image='tampa2.png' WHERE NomModele='Tampa2' AND ID_Categorie=(SELECT ID FROM categorie WHERE Libelle='Muscles');
UPDATE vehicule SET Image='vigero.png' WHERE NomModele='Vigero';
UPDATE vehicule SET Image='virgo.png' WHERE NomModele='Virgo';
UPDATE vehicule SET Image='yosemite.png' WHERE NomModele='Yosemite';
UPDATE vehicule SET Image='vamos.png' WHERE NomModele='Vamos';
UPDATE vehicule SET Image='tulip.png' WHERE NomModele='Tulip';
UPDATE vehicule SET Image='yosemite3.png' WHERE NomModele='Yosemite3';
UPDATE vehicule SET Image='voodoo.png' WHERE NomModele='Voodoo';

-- Compacts
UPDATE vehicule SET Image='asbo.png' WHERE NomModele='Asbo';
UPDATE vehicule SET Image='blista.png' WHERE NomModele='Blista';
UPDATE vehicule SET Image='blista2.png' WHERE NomModele='Blista Compact (Blista2)';
UPDATE vehicule SET Image='brioso.png' WHERE NomModele='Brioso RA (Brioso)';
UPDATE vehicule SET Image='brioso2.png' WHERE NomModele='Brioso 300 (Brioso2)';
UPDATE vehicule SET Image='club.png' WHERE NomModele='Club';
UPDATE vehicule SET Image='dilettante.png' WHERE NomModele='Dilettante';
UPDATE vehicule SET Image='issi2.png' WHERE NomModele='Issi';
UPDATE vehicule SET Image='weevil.png' WHERE NomModele='Weevil';

-- Coupes
UPDATE vehicule SET Image='cogcabrio.png' WHERE NomModele='Cognoscenti Cabrio';
UPDATE vehicule SET Image='exemplar.png' WHERE NomModele='Exemplar';
UPDATE vehicule SET Image='f620.png' WHERE NomModele='F620';
UPDATE vehicule SET Image='felon.png' WHERE NomModele='Felon';
UPDATE vehicule SET Image='felon2.png' WHERE NomModele='Felon GT';
UPDATE vehicule SET Image='windsor.png' WHERE NomModele='Windsor';
UPDATE vehicule SET Image='windsor2.png' WHERE NomModele='Windsor2';
UPDATE vehicule SET Image='zion.png' WHERE NomModele='Zion';
UPDATE vehicule SET Image='zion2.png' WHERE NomModele='Zion2';
UPDATE vehicule SET Image='zion3.png' WHERE NomModele='Zion3' AND ID_Categorie=(SELECT ID FROM categorie WHERE Libelle='Coupe');

-- Sedans
UPDATE vehicule SET Image='asea.png' WHERE NomModele='Asea';
UPDATE vehicule SET Image='asterope.png' WHERE NomModele='Asterope';
UPDATE vehicule SET Image='cheburek.png' WHERE NomModele='Cheburek';
UPDATE vehicule SET Image='cognoscenti.png' WHERE NomModele='Cognoscenti';
UPDATE vehicule SET Image='emperor.png' WHERE NomModele='Emperor';
UPDATE vehicule SET Image='emperor2.png' WHERE NomModele='Emperor2';
UPDATE vehicule SET Image='fugitive.png' WHERE NomModele='Fugitive';
UPDATE vehicule SET Image='glendale.png' WHERE NomModele='Glendale';
UPDATE vehicule SET Image='glendale2.png' WHERE NomModele='Glendale Custom';
UPDATE vehicule SET Image='intruder.png' WHERE NomModele='Intruder';
UPDATE vehicule SET Image='premier.png' WHERE NomModele='Premier';
UPDATE vehicule SET Image='primo.png' WHERE NomModele='Primo';
UPDATE vehicule SET Image='primo2.png' WHERE NomModele='Primo Custom';
UPDATE vehicule SET Image='raiden.png' WHERE NomModele='Raiden';
UPDATE vehicule SET Image='schafter2.png' WHERE NomModele='Schafter';
UPDATE vehicule SET Image='stanier.png' WHERE NomModele='Stanier';
UPDATE vehicule SET Image='stratum.png' WHERE NomModele='Stratum' AND ID_Categorie=(SELECT ID FROM categorie WHERE Libelle='Sedans');
UPDATE vehicule SET Image='surge.png' WHERE NomModele='Surge';
UPDATE vehicule SET Image='tailgater.png' WHERE NomModele='Tailgater';
UPDATE vehicule SET Image='tailgater2.png' WHERE NomModele='Tailgater2';
UPDATE vehicule SET Image='washington.png' WHERE NomModele='Washington';
UPDATE vehicule SET Image='cinquemila.png' WHERE NomModele='Cinquemila';
UPDATE vehicule SET Image='deity.png' WHERE NomModele='Deity';

-- Motos
UPDATE vehicule SET Image='avarus.png' WHERE NomModele='Avarus';
UPDATE vehicule SET Image='bagger.png' WHERE NomModele='Bagger';
UPDATE vehicule SET Image='bati.png' WHERE NomModele='Bati 801';
UPDATE vehicule SET Image='bati2.png' WHERE NomModele='Bati 801RR';
UPDATE vehicule SET Image='bf400.png' WHERE NomModele='BF400';
UPDATE vehicule SET Image='carbonrs.png' WHERE NomModele='Carbon RS';
UPDATE vehicule SET Image='cliffhanger.png' WHERE NomModele='Cliffhanger';
UPDATE vehicule SET Image='cruiser.png' WHERE NomModele='Cruiser';
UPDATE vehicule SET Image='daemon.png' WHERE NomModele='Daemon';
UPDATE vehicule SET Image='daemon2.png' WHERE NomModele='Daemon High';
UPDATE vehicule SET Image='defiler.png' WHERE NomModele='Defiler';
UPDATE vehicule SET Image='diablous.png' WHERE NomModele='Diabolus';
UPDATE vehicule SET Image='diablous2.png' WHERE NomModele='Diabolus Custom (Diabolus2)';
UPDATE vehicule SET Image='double.png' WHERE NomModele='Double T';
UPDATE vehicule SET Image='enduro.png' WHERE NomModele='Enduro';
UPDATE vehicule SET Image='esskey.png' WHERE NomModele='Esskey';
UPDATE vehicule SET Image='faggio.png' WHERE NomModele='Faggio';
UPDATE vehicule SET Image='faggio2.png' WHERE NomModele='Faggio Mod (Faggio2)';
UPDATE vehicule SET Image='fcr.png' WHERE NomModele='FCR';
UPDATE vehicule SET Image='fcr2.png' WHERE NomModele='FCR2';
UPDATE vehicule SET Image='gargoyle.png' WHERE NomModele='Gargoyle';
UPDATE vehicule SET Image='hakuchou.png' WHERE NomModele='Hakuchou';
UPDATE vehicule SET Image='hakuchou2.png' WHERE NomModele='Hakuchou Drag';
UPDATE vehicule SET Image='hexer.png' WHERE NomModele='Hexer';
UPDATE vehicule SET Image='innovation.png' WHERE NomModele='Innovation';
UPDATE vehicule SET Image='manchez.png' WHERE NomModele='Manchez';
UPDATE vehicule SET Image='nightblade.png' WHERE NomModele='Nightblade';
UPDATE vehicule SET Image='nemesis.png' WHERE NomModele='Nemesis';
UPDATE vehicule SET Image='ruffian.png' WHERE NomModele='Ruffian';
UPDATE vehicule SET Image='sanchez.png' WHERE NomModele='Sanchez';
UPDATE vehicule SET Image='sanchez2.png' WHERE NomModele='Sanchez2 (Sanchez Sport)';
UPDATE vehicule SET Image='sanctus.png' WHERE NomModele='Sanctus';
UPDATE vehicule SET Image='vader.png' WHERE NomModele='Vader';
UPDATE vehicule SET Image='vindicator.png' WHERE NomModele='Vindicator';
UPDATE vehicule SET Image='vortex.png' WHERE NomModele='Vortex';
UPDATE vehicule SET Image='wolfsbane.png' WHERE NomModele='Wolfsbane';
UPDATE vehicule SET Image='zombiea.png' WHERE NomModele='Zombie';
UPDATE vehicule SET Image='zombieb.png' WHERE NomModele='Zombie2';
UPDATE vehicule SET Image='reever.png' WHERE NomModele='Reever';
UPDATE vehicule SET Image='shinobi.png' WHERE NomModele='Shinobi';

-- SUVs
UPDATE vehicule SET Image='baller.png' WHERE NomModele='Baller Sport';
UPDATE vehicule SET Image='bjxl.png' WHERE NomModele='BJXL';
UPDATE vehicule SET Image='cavalcade.png' WHERE NomModele='Cavalcade';
UPDATE vehicule SET Image='cavalcade2.png' WHERE NomModele='Cavalcade2';
UPDATE vehicule SET Image='granger.png' WHERE NomModele='Granger';
UPDATE vehicule SET Image='gresley.png' WHERE NomModele='Gresley';
UPDATE vehicule SET Image='habanero.png' WHERE NomModele='Habanero';
UPDATE vehicule SET Image='huntley.png' WHERE NomModele='Huntley S';
UPDATE vehicule SET Image='radi.png' WHERE NomModele='Radius';
UPDATE vehicule SET Image='seminole.png' WHERE NomModele='Seminole';
UPDATE vehicule SET Image='seminole2.png' WHERE NomModele='Seminole2';
UPDATE vehicule SET Image='toros.png' WHERE NomModele='Toros';
UPDATE vehicule SET Image='novak.png' WHERE NomModele='Novak';
UPDATE vehicule SET Image='landstalker.png' WHERE NomModele='Landstalker';
UPDATE vehicule SET Image='landstalker2.png' WHERE NomModele='Landstalker2';
UPDATE vehicule SET Image='rebla.png' WHERE NomModele='Rebla';
UPDATE vehicule SET Image='rocoto.png' WHERE NomModele='Rocoto';
UPDATE vehicule SET Image='xls.png' WHERE NomModele='XLS';
UPDATE vehicule SET Image='astron.png' WHERE NomModele='Astron';
UPDATE vehicule SET Image='baller7.png' WHERE NomModele='Baller7 (Baller ST)';
UPDATE vehicule SET Image='granger2.png' WHERE NomModele='Granger2 (3600LX)';
UPDATE vehicule SET Image='iwagen.png' WHERE NomModele='Iwagen';
UPDATE vehicule SET Image='jubilee.png' WHERE NomModele='Jubilee';
UPDATE vehicule SET Image='patriot.png' WHERE NomModele='Patriot';
UPDATE vehicule SET Image='patriot2.png' WHERE NomModele='Patriot2';

-- Offroad
UPDATE vehicule SET Image='bfinjection.png' WHERE NomModele='BF Injection';
UPDATE vehicule SET Image='bifta.png' WHERE NomModele='Bifta';
UPDATE vehicule SET Image='blazer.png' WHERE NomModele='Blazer';
UPDATE vehicule SET Image='blazer4.png' WHERE NomModele='Blazer4';
UPDATE vehicule SET Image='brawler.png' WHERE NomModele='Brawler';
UPDATE vehicule SET Image='dubsta3.png' WHERE NomModele='Dubsta 6x6';
UPDATE vehicule SET Image='dloader.png' WHERE NomModele='Dloader';
UPDATE vehicule SET Image='dune.png' WHERE NomModele='Dune Buggy';
UPDATE vehicule SET Image='everon.png' WHERE NomModele='Everon';
UPDATE vehicule SET Image='guardian.png' WHERE NomModele='Guardian';
UPDATE vehicule SET Image='hellion.png' WHERE NomModele='Hellion';
UPDATE vehicule SET Image='freecrawler.png' WHERE NomModele='Freecrawler';
UPDATE vehicule SET Image='kamacho.png' WHERE NomModele='Kamacho';
UPDATE vehicule SET Image='kalahari.png' WHERE NomModele='Kalahari';
UPDATE vehicule SET Image='outlaw.png' WHERE NomModele='Outlaw';
UPDATE vehicule SET Image='rebel.png' WHERE NomModele='Rebel';
UPDATE vehicule SET Image='rebel2.png' WHERE NomModele='Rebel2';
UPDATE vehicule SET Image='riata.png' WHERE NomModele='Riata';
UPDATE vehicule SET Image='sandking.png' WHERE NomModele='Sandking';
UPDATE vehicule SET Image='sandking2.png' WHERE NomModele='Sandking2';
UPDATE vehicule SET Image='squaddie.png' WHERE NomModele='Squaddie';
UPDATE vehicule SET Image='vagrant.png' WHERE NomModele='Vagrant';
UPDATE vehicule SET Image='verus.png' WHERE NomModele='Verus';
UPDATE vehicule SET Image='caracara2.png' WHERE NomModele='Caracara2';

-- Vans / Utilitaires
UPDATE vehicule SET Image='bison.png' WHERE NomModele='Bison';
UPDATE vehicule SET Image='bison2.png' WHERE NomModele='Bison2';
UPDATE vehicule SET Image='burrito2.png' WHERE NomModele='Burrito2';
UPDATE vehicule SET Image='burrito3.png' WHERE NomModele='Burrito3';
UPDATE vehicule SET Image='burrito4.png' WHERE NomModele='Burrito4';
UPDATE vehicule SET Image='gburrito.png' WHERE NomModele='Gang Burrito';
UPDATE vehicule SET Image='bobcatxl.png' WHERE NomModele='Bobcat XL';
UPDATE vehicule SET Image='speedo.png' WHERE NomModele='Speedo';
UPDATE vehicule SET Image='speedo2.png' WHERE NomModele='Speedo2';
UPDATE vehicule SET Image='rumpo.png' WHERE NomModele='Rumpo';
UPDATE vehicule SET Image='rumpo2.png' WHERE NomModele='Rumpo2';
UPDATE vehicule SET Image='rumpo3.png' WHERE NomModele='Rumpo3';
UPDATE vehicule SET Image='moonbeam.png' WHERE NomModele='Moonbeam';
UPDATE vehicule SET Image='moonbeam2.png' WHERE NomModele='Moonbeam Rider';
UPDATE vehicule SET Image='youga.png' WHERE NomModele='Youga';
UPDATE vehicule SET Image='youga2.png' WHERE NomModele='Youga2';
UPDATE vehicule SET Image='youga3.png' WHERE NomModele='Youga3';
UPDATE vehicule SET Image='youga4.png' WHERE NomModele='Youga4';
UPDATE vehicule SET Image='boxville.png' WHERE NomModele='Boxville';
UPDATE vehicule SET Image='boxville2.png' WHERE NomModele='Boxville2';
UPDATE vehicule SET Image='boxville3.png' WHERE NomModele='Boxville3';
UPDATE vehicule SET Image='mule.png' WHERE NomModele='Mule';
UPDATE vehicule SET Image='mule2.png' WHERE NomModele='Mule2';
UPDATE vehicule SET Image='mule3.png' WHERE NomModele='Mule3';
UPDATE vehicule SET Image='benson.png' WHERE NomModele='Benson';
UPDATE vehicule SET Image='speedo4.png' WHERE NomModele='New Speedo (nspeedo)';
UPDATE vehicule SET Image='burrito5.png' WHERE NomModele='Burrito6';

-- Boats
UPDATE vehicule SET Image='dinghy.png' WHERE NomModele='Dinghy';
UPDATE vehicule SET Image='dinghy2.png' WHERE NomModele='Dinghy2';
UPDATE vehicule SET Image='dinghy4.png' WHERE NomModele='Dinghy4';
UPDATE vehicule SET Image='jetmax.png' WHERE NomModele='Jetmax';
UPDATE vehicule SET Image='marquis.png' WHERE NomModele='Marquis';
UPDATE vehicule SET Image='seashark.png' WHERE NomModele='Seashark';
UPDATE vehicule SET Image='seashark2.png' WHERE NomModele='Seashark2';
UPDATE vehicule SET Image='speeder.png' WHERE NomModele='Speeder';
UPDATE vehicule SET Image='speeder2.png' WHERE NomModele='Speeder2';
UPDATE vehicule SET Image='squalo.png' WHERE NomModele='Squalo';
UPDATE vehicule SET Image='suntrap.png' WHERE NomModele='Suntrap';
UPDATE vehicule SET Image='toro2.png' WHERE NomModele='Toro2';
UPDATE vehicule SET Image='tropic.png' WHERE NomModele='Tropic';
UPDATE vehicule SET Image='tropic2.png' WHERE NomModele='Tropic2';
UPDATE vehicule SET Image='longfin.png' WHERE NomModele='Longfin';
UPDATE vehicule SET Image='patrolboat.png' WHERE NomModele='Patrol Boat';
UPDATE vehicule SET Image='kosatka.png' WHERE NomModele='Kraken';
UPDATE vehicule SET Image='dinghy3.png' WHERE NomModele='Catalina Dinghy';
UPDATE vehicule SET Image='submersible.png' WHERE NomModele='Submersible';
UPDATE vehicule SET Image='toro.png' WHERE NomModele='Yacht SR650 (sr650fly)';

-- Aircraft
UPDATE vehicule SET Image='cuban800.png' WHERE NomModele='Cuban 800';
UPDATE vehicule SET Image='dodo.png' WHERE NomModele='Dodo';
UPDATE vehicule SET Image='frogger.png' WHERE NomModele='Frogger';
UPDATE vehicule SET Image='frogger2.png' WHERE NomModele='Frogger2';
UPDATE vehicule SET Image='havok.png' WHERE NomModele='Havok';
UPDATE vehicule SET Image='mammatus.png' WHERE NomModele='Mammatus';
UPDATE vehicule SET Image='microlight.png' WHERE NomModele='Microlight';
UPDATE vehicule SET Image='velum.png' WHERE NomModele='Velum';
UPDATE vehicule SET Image='velum2.png' WHERE NomModele='Velum2';
UPDATE vehicule SET Image='vestra.png' WHERE NomModele='Vestra';
UPDATE vehicule SET Image='swift.png' WHERE NomModele='Swift';
UPDATE vehicule SET Image='luxordeluxe.png' WHERE NomModele='Swift Deluxe';
UPDATE vehicule SET Image='supervolito2.png' WHERE NomModele='SuperVolito2';
UPDATE vehicule SET Image='volatus.png' WHERE NomModele='Volatus';
UPDATE vehicule SET Image='alphaz1.png' WHERE NomModele='Alpha-Z1';
UPDATE vehicule SET Image='alkonost.png' WHERE NomModele='Alkonost';
UPDATE vehicule SET Image='annihilator.png' WHERE NomModele='Annihilator';
UPDATE vehicule SET Image='annihilatorstealth.png' WHERE NomModele='Annihilator Stealth';
UPDATE vehicule SET Image='buzzard.png' WHERE NomModele='Buzzard';
UPDATE vehicule SET Image='cargobob.png' WHERE NomModele='Cargobob';
UPDATE vehicule SET Image='cargobob2.png' WHERE NomModele='Cargobob2';
UPDATE vehicule SET Image='cargobob3.png' WHERE NomModele='Cargobob3';
UPDATE vehicule SET Image='cargobob4.png' WHERE NomModele='Cargobob4';
UPDATE vehicule SET Image='duster.png' WHERE NomModele='Duster';
UPDATE vehicule SET Image='luxor.png' WHERE NomModele='Luxor';
UPDATE vehicule SET Image='luxordeluxe.png' WHERE NomModele='Luxor Deluxe';
UPDATE vehicule SET Image='tula.png' WHERE NomModele='Tula';
UPDATE vehicule SET Image='skylift.png' WHERE NomModele='Skylift';
UPDATE vehicule SET Image='seasparrow.png' WHERE NomModele='Seasparrow';
UPDATE vehicule SET Image='seasparrow2.png' WHERE NomModele='Seasparrow2';
UPDATE vehicule SET Image='nimbus.png' WHERE NomModele='Mallard';

UPDATE vehicule SET Image='comet2.png' WHERE NomModele='Comet';
UPDATE vehicule SET Image='swift2.png' WHERE NomModele='Swift Deluxe';
UPDATE vehicule SET Image='growler.png' WHERE NomModele='Growler RR';
UPDATE vehicule SET Image='sheava.png' WHERE NomModele='ETR1';